version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
#    volumes:
#      - .:/app

networks:
  app-network:
