spring:
  config:
    activate:
      on-profile: prod

  server:
    port: ${PORT:8080}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 600000       # 10 minutos
    max-lifetime: 1800000      # 30 minutos
    connection-timeout: 30000  # 30 segundos
    auto-commit: true
    data-source-properties:
      prepareThreshold: 0


app:
  jwtSecret: ${JWT_SECRET}
